---
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: chart-pull-secret
spec:
  externalSecretName: "chart-pull-secret"
  refreshTime: "1m"
  namespaceSelector: {}
  externalSecretSpec:
    secretStoreRef:
      name: vault-admin
      kind: ClusterSecretStore
    target:
      name: "chart-pull-secret"
    data:
      - secretKey: "username"
        remoteRef:
          key: "secret/svc/github"
          property: "token_username"
      - secretKey: "password"
        remoteRef:
          key: "secret/svc/github"
          property: "image_pull_token"
