---
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: registry-credential
spec:
  externalSecretName: "registry-credential"
  refreshTime: "1m"
  namespaceSelector: {}
  externalSecretSpec:
    secretStoreRef:
      name: vault-admin
      kind: ClusterSecretStore
    target:
      name: "registry-credential"
      template:
        type: "kubernetes.io/dockerconfigjson"
        engineVersion: "v2"
        data:
          .dockerconfigjson: |
            {
              "auths": {
                "ghcr.io/ianhewlett": {
                  "auth": "{{ `{{ printf "%s%s" "username:" .pat | b64enc }}` }}"
                }
              }
            }
    data:
      - secretKey: "pat"
        remoteRef:
          key: "secret/svc/github"
          property: "image_pull_token"
