---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - ../../../release/external-secrets
patches:
  - target:
      kind: Application
      name: external-secrets
    patch: |
      - op: add
        path: /spec/sources/0/helm/valueFiles/-
        value:
          $values/environments/local/values.yaml
