---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-admin
spec:
  provider:
    vault:
      server: <path:avp/data/test#sample>
      path: secret
      version: v2
      auth:
        kubernetes:
          mountPath: "{{ .Values.clusterName }}"
          role: "di-admin-kubernetes-role"
      namespace: admin
