---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-admin
spec:
  provider:
    vault:
      server: <path:test/svc/vault#vault_address>
      path: secret
      version: v2
      auth:
        kubernetes:
          mountPath: "${CLUSTER_NAME}"
          role: "di-admin-kubernetes-role"
      namespace: admin
